# Generated by Codex on 2026-05-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pet_accessory',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'item_type': 'pet_accessory'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='pet_accessory_users',
                to='shop.shopitem',
                verbose_name='Аксессуар питомца',
            ),
        ),
    ]
