# Generated by Codex on 2026-05-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shopitem_item_type'),
        ('accounts', '0003_user_pet_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pet_color',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'item_type': 'pet_color'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='pet_color_users',
                to='shop.shopitem',
                verbose_name='Расцветка питомца',
            ),
        ),
    ]
