# Generated by Django 5.0.4 on 2026-05-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='condition_type',
            field=models.CharField(choices=[('tasks_completed', 'Всего выполнено задач'), ('tasks_total', 'Всего выполнено задач'), ('streak_days', 'Серия дней'), ('level_reached', 'Достигнут уровень'), ('coins_earned', 'Монет заработано всего')], max_length=30, verbose_name='Тип условия'),
        ),
    ]
