# Generated by Django 5.0.4 on 2026-02-27 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('item_type', models.CharField(choices=[('avatar', 'Аватар'), ('theme', 'Тема интерфейса'), ('shield', 'Щит серии')], max_length=20, verbose_name='Тип')),
                ('price', models.PositiveIntegerField(verbose_name='Цена (монеты)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/', verbose_name='Изображение')),
                ('css_class', models.CharField(blank=True, max_length=50, verbose_name='CSS класс темы')),
                ('is_default', models.BooleanField(default=False, verbose_name='Доступен по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен в магазине')),
            ],
            options={
                'verbose_name': 'Товар магазина',
                'verbose_name_plural': 'Товары магазина',
                'ordering': ['item_type', 'price'],
            },
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Куплено')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='shop.shopitem', verbose_name='Предмет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Инвентарь пользователя',
                'verbose_name_plural': 'Инвентарь пользователей',
                'unique_together': {('user', 'item')},
            },
        ),
    ]
