# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shopitem_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='item_type',
            field=models.CharField(
                choices=[
                    ('avatar', 'Аватар'),
                    ('theme', 'Тема интерфейса'),
                    ('shield', 'Щит серии'),
                    ('pet_accessory', 'Аксессуар питомца'),
                    ('pet_color', 'Расцветка питомца'),
                ],
                max_length=20,
                verbose_name='Тип',
            ),
        ),
    ]
